# name: Build and publish to pages
# on:
#   push:
#     branches:
#     - main

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@master
#       with:
#         fetch-depth: 1
#     - name: seupEmacs
#       # uses: docker://iquiw/alpine-emacs
#       uses: purcell/setup-emacs@master
#       # if: github.event.deleted == false
#       with:
#         # args: ./publishWeb.sh
#         version: 28.1
#     - name: run
#       run: ./publishWeb.sh
#     - name: deploy
#       uses: peaceiris/actions-gh-pages@v3
#       if: success()
#       with:
#         github_token: ${{ secrets.API_TOKEN_GITHUB }}
#         publish_dir: ./public

name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: runcode.tex
          latexmk_shell_escape: true
        # - uses: actions/upload-artifact@v2
        #   with:
        #     name: PDF
        #     path: runcode.pdf
